### PR TITLE
refactored dry run arg, added argparse, fixed peering connection delete

### PR DESCRIPTION
**Pull request by torrencj**
- Added argparse, now the script runs dry unless the `--not-dry-run` flag is present
- Cleaned up the peering connection search and ensured that it finds the correct one
- Hard coded the test account ID more thoroughly
- Renamed the file

### CODE REVIEW

**Comment by torrencj** [comment]
@dangq89 yo man you going to approve this?

**Comment by dangq89** [comment]
@torrencj are you getting this man?

**Comment by torrencj** [comment]
@dangq89 you gotta merge this, man

**Comment by dangq89** [comment]
my bad lol merged!

**Pull request merged**
